# docker run --restart always --privileged=true --name Jenkins  --publish 8000:8080  --publish 50000:50000  -e JENKINS_OPTS="--prefix=/jenkins"  --mount type=volume,src=jenkins,dst=/var/jenkins_home -v /var/run/docker.sock:/var/run/docker.sock jenkins/jenkins:lts

version: '3.2'
services:
  db:
    image: mysql:5.7
    command: --max_allowed_packet=32505856
    networks:
     - cicd_default
    container_name: sonarmysql
    environment:
     - MYSQL_ROOT_HOST=%
     - MYSQL_ROOT_PASSWORD=sonar
     - MYSQL_DATABASE=sonar
     - MYSQL_USER=sonar
     - MYSQL_PASSWORD=sonar
    volumes:
     - sonarmysql_db:/var/lib/mysql

  sonarqube:
    image: sonarqube:lts
    command: -Dsonar.web.context=/sonarqube
    restart: always
    ports:
      - 7000:9000
      - 7092:9092
    container_name: sonarqube
    environment:
     - SONARQUBE_JDBC_USERNAME=sonar
     - SONARQUBE_JDBC_PASSWORD=sonar
     - SONARQUBE_JDBC_URL=jdbc:mysql://sonarmysql:3306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance&useSSL=false
    volumes:
     - sonar_ext:/opt/sonarqube/extensions
    networks:
     - cicd_default 
    depends_on:
     - db
  
  jenkins:
    build: 
      context: jenkins
    restart: always
    environment:
     - JENKINS_OPTS= '--prefix=/jenkins'
    privileged: 'true'
    user: root
    ports:
      - 7080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - jenkins:/var/jenkins_home 
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
     - cicd_default
volumes:
  jenkins:
  sonarmysql_db:
  sonar_ext:

networks:
  cicd_default:
    external: true
