version: '3.7'

services:
  portainer:
    image: portainer/portainer:latest
    restart: always
    container_name: "portainer"
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:
